networks:
  jellyfin_network:
    ipam:
      config:
        - subnet: 172.30.0.0/24

volumes:
  postgres-data: null
  jellystat-backup-data: null

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /docker/jellyfin/library:/config
      - /mnt/data/anime:/data/anime
      - /mnt/data/movies:/data/movies
      - /mnt/data/music:/data/music
      - /mnt/data/series:/data/tvshows
    ports:
      - 8096:8096   # Jellyfin web interface
      - 1900:1900/udp  # DLNA / discovery
      - 7359:7359/udp  # DLNA
    networks:
      jellyfin_network:
        ipv4_address: 172.30.0.20

  jellystat-db:
    image: postgres:15.2
    container_name: jellystat-db
    restart: unless-stopped
    env_file:
      - /mnt/docker/jellyfin/.env
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    networks:
      jellyfin_network:
        ipv4_address: 172.30.0.21

  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    restart: unless-stopped
    env_file:
      - /mnt/docker/jellyfin/.env
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - jellystat-backup-data:/app/backend/backup-data
    ports:
      - "3000:3000"
    depends_on:
      - jellystat-db
    networks:
      jellyfin_network:
        ipv4_address: 172.30.0.22
