---
title: "Homelab"
subtitle: "Pym"
logo: "logo.png"

header: True
footer: false

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg"
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

# tagstyle: is-link, is-info, is-success, is-warning or is-danger!
services:
  - name: "//Managment"
    icon: "fa-solid fa-server"
    items:
      - name: "Proxmox"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/proxmox.png"
        subtitle: "Server virtualization management solution"
        tag: "proxmox"
        tagstyle: "is-link"
        url: "https://192.168.50.200:8006/"
        target: "_blank"
      - name: "Pi-hole"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/pi-hole.png"
        subtitle: "AD-Blocking DNS"
        tag: "pihole"
        tagstyle: "is-link"
        url: "https://192.168.50.14/admin/login"
        target: "_blank"
  - name: "//Servarr"
    icon: "fa-solid fa-server"
    items:
      - name: "Prowlarr"
        logo: "https://prowlarr.com/logo/128.png"
        subtitle: "The Ultimate Indexer Manager"
        tag: "prowlarr"
        tagstyle: "is-link"
        url: "http://192.168.50.205:9696"
        target: "_blank"
      - name: "Radarr"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/radarr.png"
        subtitle: "Movie collection manager"
        tag: "radarr"
        tagstyle: "is-link"
        url: "http://192.168.50.205:7878"
        target: "_blank"
      - name: "Sonarr"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/sonarr.png"
        subtitle: "TV Shows collection manager"
        tag: "sonarr"
        tagstyle: "is-link"
        url: "http://192.168.50.205:8989"
        target: "_blank"
      - name: "Readarr"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/readarr.png"
        subtitle: "Books collection manager"
        tag: "readarr"
        tagstyle: "is-link"
        url: "http://192.168.50.205:8787"
        target: "_blank"
      - name: "Bazarr"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/bazarr.png"
        subtitle: "Subtitles manager"
        tag: "bazarr"
        tagstyle: "is-link"
        url: "http://192.168.50.205:6767"
        target: "_blank"
  - name: "//Media"
    icon: "fa-solid fa-play"
    items:
      - name: "Jellyfin"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyfin.png"
        subtitle: "Media server"
        tag: "jellyfin"
        tagstyle: "is-link"
        url: "http://192.168.50.205:8096/"
        target: "_blank"
      - name: "Jellyseerr"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyseerr.png"
        subtitle: "Manage requests for media library"
        tag: "jellyseerr"
        tagstyle: "is-link"
        url: "http://192.168.50.205:5055/"
        target: "_blank"
      - name: "Jellystat"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellystat.png"
        subtitle: "Statistics App for Jellyfin"
        tag: "jellystat"
        tagstyle: "is-link"
        url: "http://192.168.50.205:3000/"
        target: "_blank"
  - name: "//Download"
    icon: "fa-solid fa-download"
    items:
      - name: "qBittorrent"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/qbittorrent.png"
        subtitle: "Torrent downloader"
        tag: "qbittorrent"
        tagstyle: "is-link"
        url: "http://192.168.50.205:8080/"
        target: "_blank"
      - name: "YTDL-SUB"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/youtube-dl.png"
        subtitle: "Youtube downloader"
        tag: "ytdl"
        tagstyle: "is-link"
        url: "http://192.168.50.205:8443/"
        target: "_blank"
  - name: "//Browser"
    icon: "fa-solid fa-folder-tree"
    items:
      - name: "File Browser"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/file-explorer.png"
        subtitle: "Web based File Browser"
        tag: "filebrowser"
        tagstyle: "is-link"
        url: "http://192.168.50.205"
        target: "_blank"

